services:
  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    container_name: database 
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    hostname: rm_database
    networks:
      - net_rm_database
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5
# ----------------------------------------------------------------------------
  # - The adminer is a tool for managing content in database
  adminer:
    image: adminer
    container_name: adminer_rm
    restart: always
    ports:
      - 8080:8080
    networks:
      - net_rm_database
# ----------------------------------------------------------------------------
  # - fastapi refers to the container where the application backend will be stored.
  fastapi:
    build: 
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: backend_rm
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_rm_database 
# ----------------------------------------------------------------------------
networks:
  net_rm_database:
    driver: bridge
    name: net_rm_database